language: objective-c
script: "brew install optipng && cd test && bash test.sh && git status | grep 'working directory clean'"
branches:
  only:
    - master
notifications:
  email:
    - andrew@andrewschaaf.com
